title: 'The World for Net Neutrality'
url: https://www.theworldfornetneutrality.com/
share_title: "International organizations for net neutrality"
share_description: "If you run a company outside the U.S., sign this letter and make sure your voice is heard in this fight."
fb_share_image: "/images/world4nn-og.png"

# Build settings
#sass:
#  sass_dir: ./_scss
markdown: kramdown
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
