title: 'The World for Net Neutrality'
url: https://www.theworldfornetneutrality.com/
share_title: "Over 200 international organizations for net neutrality"
share_description: "Companies and organizations outside the US are worried what a loss of net neutrality could mean for the global Internet. Learn more here."
fb_share_image: "/images/keepthewebopen-og2.png"

# Build settings
#sass:
#  sass_dir: ./_scss
markdown: kramdown
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
